---
plugins:
  - rubocop-minitest
  - rubocop-rake

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable

Naming/VariableNumber:
  Enabled: false

Layout/LineLength:
  Max: 120

Metrics/ClassLength:
  Exclude:
    - 'test/test_*'
